db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: npm run nodemon
  dockerfile: Dockerfile.local
  environment:
    PORT: 3000
    DATABASE_URL: 'db:27017/geohash-notifier'
  links:
    - db
  ports:
    - "3000:3000"
  volumes:
    - .:/app
    - /app/node_modules
